### PR TITLE
Improve docker container

### PR DESCRIPTION
**Pull request by TheSilkky**

### CODE REVIEW

**Review by No767 — COMMENTED** [review]
also note that if someone is running this, they will have to get the api keys and access tokens (some require OAuth2), and then they will have to add like 15 `-e` flags just to run the bot

**Comment by TheSilkky** [comment]
I thought those keys were required for Rin to actually boot?

**Comment by No767** [comment]
Only the bot token is required. The API Keys and Access tokens are used on request to the api

**Comment by TheSilkky** [comment]
If not you can probably just remove the `exit 1` from the start script

**Comment by No767** [comment]
ah ok just did

**Comment by TheSilkky** [comment]
ok it still might be broken because of the placeholder values in .env.example

**Comment by No767** [comment]
ah ok. gonna go ahead and check rn

**Comment by No767** [comment]
also just noticed that python-dotenv reads off of .env files. so...

**Review by No767 — APPROVED** [review]

**Comment by No767** [comment]
will be merging the pr either tmmr morning, or at like 4am if im on my phone

**Comment by No767** [comment]
seems to be working fine. Merging pr

**Comment by No767** [comment]
also should have left the old dockerfile in place for compat reasons for kumiko

**Pull request merged**
